import { Request, Response } from 'express';
import { supabase } from '../lib/supabaseClient';
import { catchAsync, UnauthorizedError } from '../utils/appErrors';

/**
 * GET /api/narratives
 * Get user's saved Axiom narratives (from axiom_daily_briefs table)
 */
export const getNarratives = catchAsync(async (req: Request, res: Response) => {
  const userId = req.user?.id;
  if (!userId) throw new UnauthorizedError('Not authenticated');

  const { limit = '50' } = req.query as { limit?: string };

  const { data, error } = await supabase
    .from('axiom_daily_briefs')
    .select('date, brief, generated_at')
    .eq('user_id', userId)
    .order('date', { ascending: false })
    .limit(Math.min(parseInt(limit, 10) || 50, 200));

  if (error) throw error;

  // Transform to narrative-like format
  const narratives = (data || []).map(brief => {
    const b = typeof brief.brief === 'string' ? JSON.parse(brief.brief) : (brief.brief || {});
    return {
      id: brief.date, // use date as ID
      narrative_type: 'daily_brief',
      title: b.title || `Axiom Brief - ${brief.date}`,
      created_at: brief.generated_at,
      brief: b,
      date: brief.date,
    };
  });

  res.json(narratives);
});

/**
 * GET /api/narratives/:id
 * Get single narrative with full content (by date from axiom_daily_briefs)
 */
export const getNarrative = catchAsync(async (req: Request, res: Response) => {
  const userId = req.user?.id;
  if (!userId) throw new UnauthorizedError('Not authenticated');

  const { id } = req.params; // this is actually the date

  const { data, error } = await supabase
    .from('axiom_daily_briefs')
    .select('date, brief, generated_at')
    .eq('user_id', userId)
    .eq('date', id)
    .single();

  if (error) {
    if (error.code === 'PGRST116') {
      return res.status(404).json({ message: 'Brief not found' });
    }
    throw error;
  }

  const b = typeof data.brief === 'string' ? JSON.parse(data.brief) : (data.brief || {});
  res.json({
    id: data.date,
    narrative_type: 'daily_brief',
    title: b.title || `Axiom Brief - ${data.date}`,
    content: b.content || '',
    brief: b,
    date: data.date,
    created_at: data.generated_at,
  });
});

/**
 * GET /api/narratives/:id/download
 * Download brief as markdown file
 */
export const downloadNarrative = catchAsync(async (req: Request, res: Response) => {
  const userId = req.user?.id;
  if (!userId) throw new UnauthorizedError('Not authenticated');

  const { id } = req.params; // this is actually the date

  const { data, error } = await supabase
    .from('axiom_daily_briefs')
    .select('date, brief')
    .eq('user_id', userId)
    .eq('date', id)
    .single();

  if (error) {
    if (error.code === 'PGRST116') {
      return res.status(404).json({ message: 'Brief not found' });
    }
    throw error;
  }

  const b = typeof data.brief === 'string' ? JSON.parse(data.brief) : (data.brief || {});
  const title = b.title || `Axiom Brief - ${data.date}`;
  const content = b.content || '';
  const briefDate = data.date || '';

  // Convert to markdown
  const md = `# ${title}\n\n_${briefDate}_\n${content}\n\n---\n*Generated by Axiom AI*`;

  res.setHeader('Content-Type', 'text/markdown');
  res.setHeader('Content-Disposition', `attachment; filename="${title.replace(/[^a-z0-9]/gi, '-')}.md"`);
  res.send(md);
});
